version: '3'


services:
  #reverseproxy:
  #  image: nginx:latest
  #  container_name: reverseproxy
  #  volumes:
  #    - /host/path/nginx.conf:/etc/nginx/nginx.conf
  #  ports:
  #    - 80:80


  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
    - /data/influxdb:/var/lib/influxdb
    ports:
    - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=supersecretpassword
      - INFLUXDB_USER=influxdb
      - INFLUXDB_USER_PASSWORD=secretpassword


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
    - 3000:3000

  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - 18083:18083
      - 1883:1883
      - 4369:4369

  influxdb_mqtt_bridge:
    build:
      context: ..
      dockerfile: ./influxDBPusher.Dockerfile
    container_name: influxdb_bridge
    ports:
      - 8000:8000
    environment:
      - MQTT_BROKER_ADR=emqx
      - INFLUXDB_ADR=influxdb
      - INFLUXDB_USERNAME=influxdb
      - INFLUXDB_PASSWORD=secretpassword
    depends_on:
      - influxdb
      - grafana
      - emqx

  mqtt_producer:
    build:
      context: ./
      dockerfile: mqtt_producer.Dockerfile
    container_name: mqtt_producer
    environment:
      - MQTT_BROKER_ADR=emqx
    depends_on:
      - emqx

  # missing:
  # web application
  # Linuxmonitoring Container